
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: flunders.wardle.example.com
spec:
  group: wardle.example.com
  names:
    kind: Flunder
    listKind: FlunderList
    plural: flunders
    singular: flunder
  preserveUnknownFields: false
  scope: Namespaced
  validation:
    openAPIV3Schema:
      description: Flunder is an example type with a spec and a status.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: FlunderSpec is the specification of a Flunder.
          properties:
            fischerReference:
              description: A name of a fischer, mutually exclusive to the FlunderReference.
              type: string
            flunderReference:
              description: A name of another flunder, mutually exclusive to the FischerReference.
              type: string
            referenceType:
              description: The reference type.
              type: string
          type: object
        status:
          description: FlunderStatus is the status of a Flunder.
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: false
  - name: v1beta1
    served: true
    storage: true
