apiVersion: meta.k8s.appscode.com/v1alpha1
kind: ResourceQuery
request:
  source:
    resource:
      group: apps
      version: v1
      name: deployments
    name: kube-ui-server
    namespace: kubeops
  # Ref;Object;Table
  outputFormat: Object
  target:
    query:
      byLabel: offshoot
      type: GraphQL
    ref:
      group: apps
      kind: ReplicaSet
