
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: offlinelicenses.offline.licenses.appscode.com
spec:
  group: offline.licenses.appscode.com
  names:
    kind: OfflineLicense
    listKind: OfflineLicenseList
    plural: offlinelicenses
    singular: offlinelicense
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Status
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          status:
            description: OfflineLicenseStatus defines the observed state of OfflineLicense
            properties:
              license:
                description: License defines a AppsCode product license info.
                properties:
                  apiVersion:
                    description: 'APIVersion defines the versioned schema of this
                      representation of an object. Servers should convert recognized
                      schemas to the latest internal value, and may reject unrecognized
                      values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
                    type: string
                  clusters:
                    items:
                      type: string
                    type: array
                  featureFlags:
                    additionalProperties:
                      type: string
                    type: object
                  features:
                    items:
                      type: string
                    type: array
                  id:
                    type: string
                  issuer:
                    type: string
                  kind:
                    description: 'Kind is a string value representing the REST resource
                      this object represents. Servers may infer this from the endpoint
                      the client submits requests to. Cannot be updated. In CamelCase.
                      More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
                    type: string
                  notAfter:
                    format: date-time
                    type: string
                  notBefore:
                    format: date-time
                    type: string
                  planName:
                    type: string
                  productLine:
                    type: string
                  reason:
                    type: string
                  status:
                    enum:
                    - unknown
                    - active
                    - invalid
                    - canceled
                    type: string
                  tierName:
                    type: string
                  user:
                    properties:
                      email:
                        type: string
                      name:
                        type: string
                    required:
                    - email
                    - name
                    type: object
                required:
                - reason
                - status
                type: object
              secretKeyRef:
                description: SecretKeySelector selects a key of a Secret.
                properties:
                  key:
                    description: The key of the secret to select from.  Must be a
                      valid secret key.
                    type: string
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                  optional:
                    description: Specify whether the Secret or its key must be defined
                    type: boolean
                required:
                - key
                type: object
                x-kubernetes-map-type: atomic
            required:
            - license
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
