apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-server
  namespace: identity
  labels:
    apiserver: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      apiserver: "true"
  template:
    metadata:
      labels:
        apiserver: "true"
    spec:
      serviceAccountName: apiserver
      containers:
      - name: identity-server
        # build from staging/src/kubeshield.dev/identity-server/artifacts/simple-image/Dockerfile
        # or
        # docker pull gcr.io/kubernetes-e2e-test-images/sample-apiserver:1.17
        # docker tag gcr.io/kubernetes-e2e-test-images/sample-apiserver:1.17 kube-sample-apiserver:latest
        image: kube-sample-apiserver:latest
        imagePullPolicy: Never
        args: [ "--etcd-servers=http://localhost:2379" ]
      - name: etcd
        image: quay.io/coreos/etcd:v3.4.4
