#apiVersion: meta.k8s.appscode.com/v1alpha1
#kind: RenderRawGraph
#request:
#  source:
#    resource:
#      group: kubedb.com
#      version: v1
#      name: postgreses
#    ref:
#      name: ace-db
#      namespace: ace


apiVersion: meta.k8s.appscode.com/v1alpha1
kind: RenderRawGraph
request:
  source:
    resource:
      group: ""
      version: v1
      name: pods
    ref:
      name: ace-db-0
      namespace: ace
  # source:
  #   resource:
  #     group: ui.kubedb.com
  #     version: v1alpha1
  #     kind: ElasticsearchInsight
  #   ref:
  #     name: es-test
  #     namespace: demo
