apiVersion: meta.k8s.appscode.com/v1alpha1
kind: RenderPage
request:
  convertToTable: true
  pageName: Basic
  source:
    group: apps
    kind: Deployment
    name: coredns
    namespace: kube-system
response:
  sections:
  - resource:
      group: apps
      kind: ReplicaSet
      name: replicasets
      scope: Namespaced
      version: v1
    table:
      columnDefinitions:
      - name: Name
        type: string
      - name: Namespace
        type: string
      - name: Labels
        type: object
      - name: Pods
        type: string
      - name: Images
        type: string
      - name: Age
        type: date
      metadata: {}
      rows:
      - cells:
        - coredns-64897985d
        - kube-system
        - k8s-app: kube-dns
          pod-template-hash: 64897985d
        - 2/2
        - ""
        - 4h9m
  - resource:
      group: ""
      kind: Pod
      name: pods
      scope: Namespaced
      version: v1
    table:
      columnDefinitions:
      - format: name
        name: Name
        type: string
      - name: Namespace
        type: string
      - name: Labels
        type: object
      - name: Ready
        type: string
      - name: Status
        type: string
      - name: Restarts
        type: integer
      - name: IP
        type: string
      - name: Node
        type: string
      - name: Images
        type: string
      - name: Age
        type: date
      metadata: {}
      rows:
      - cells:
        - coredns-64897985d-8hsxf
        - kube-system
        - k8s-app: kube-dns
          pod-template-hash: 64897985d
        - 1/1
        - Running
        - 0
        - 10.244.0.2
        - kind-control-plane
        - ""
        - 4h9m
      - cells:
        - coredns-64897985d-cs7zq
        - kube-system
        - k8s-app: kube-dns
          pod-template-hash: 64897985d
        - 1/1
        - Running
        - 0
        - 10.244.0.4
        - kind-control-plane
        - ""
        - 4h9m
  - resource:
      group: ""
      kind: Service
      name: services
      scope: Namespaced
      version: v1
    table:
      columnDefinitions:
      - name: Name
        type: string
      - name: Namespace
        type: string
      - name: Labels
        type: object
      - name: Type
        type: string
      - name: Cluster-IP
        type: string
      - name: External-IP
        type: string
      - name: Port(s)
        type: string
      - name: Selector
        type: string
      - name: Age
        type: string
      metadata: {}
      rows:
      - cells:
        - kube-dns
        - kube-system
        - k8s-app: kube-dns
          kubernetes.io/cluster-service: "true"
          kubernetes.io/name: CoreDNS
        - ClusterIP
        - 10.96.0.10
        - <none>
        - 53/UDP,53/TCP,9153/TCP
        - k8s-app=kube-dns
        - 4h9m
  - resource:
      group: autoscaling
      kind: HorizontalPodAutoscaler
      name: horizontalpodautoscalers
      scope: Namespaced
      version: v2
    table:
      columnDefinitions:
      - name: Name
        type: string
      - name: Namespace
        type: string
      - name: Labels
        type: object
      - name: Annotations
        type: object
      - name: Age
        type: date
      metadata: {}
      rows: []
