apiVersion: meta.k8s.appscode.com/v1alpha1
kind: RenderSection
request:
  convertToTable: true
  source:
    group: apps
    kind: Deployment
    name: coredns
    namespace: kube-system
  target:
    query:
      byLabel: offshoot
    ref:
      group: apps
      kind: ReplicaSet
response:
  resource:
    group: apps
    kind: ReplicaSet
    name: replicasets
    scope: Namespaced
    version: v1
  table:
    columnDefinitions:
    - name: Name
      type: string
    - name: Namespace
      type: string
    - name: Labels
      type: object
    - name: Pods
      type: string
    - name: Images
      type: string
    - name: Age
      type: date
    metadata: {}
    rows:
    - cells:
      - coredns-64897985d
      - kube-system
      - k8s-app: kube-dns
        pod-template-hash: 64897985d
      - 2/2
      - ""
      - 4h9m
