apiVersion: meta.k8s.appscode.com/v1alpha1
kind: Render
request:
  convertToTable: true
  layoutName: core-v1-pods
  pageName: Basic
  renderBlocks:
  - Self
  source:
    ref:
      name: mg-rs-0
      namespace: default
    resource:
      group: core
      kind: ""
      name: pods
      scope: ""
      version: v1
response:
  view:
    layoutName: core-v1-pods
    pages:
    - info:
        kind: Self
        resource:
          group: ""
          kind: Pod
          name: pods
          scope: Namespaced
          version: v1
        result:
          status: Success
        table:
          columns:
          - name: Name
            priority: 3
            sort:
              enable: true
            type: string
          - name: Namespace
            priority: 3
            type: string
          - name: Labels
            priority: 3
            type: object
          - name: Annotations
            priority: 3
            type: object
          - name: Age
            priority: 3
            sort:
              enable: true
              type: integer
            type: date
          metadata:
            resourceVersion: "128935"
          rows:
          - cells:
            - data: mg-rs-0
            - data: default
            - data:
                app.kubernetes.io/component: database
                app.kubernetes.io/instance: mg-rs
                app.kubernetes.io/managed-by: kubedb.com
                app.kubernetes.io/name: mongodbs.kubedb.com
                controller-revision-hash: mg-rs-7d7d5b6fc7
                kubedb.com/role: primary
                statefulset.kubernetes.io/pod-name: mg-rs-0
            - data:
                cni.projectcalico.org/podIP: 10.2.3.5/32
                cni.projectcalico.org/podIPs: 10.2.3.5/32
            - data: 13d
              sort: 1646039114
      name: Basic
    resource:
      group: ""
      kind: Pod
      name: pods
      scope: Namespaced
      version: v1
    ui:
      editor:
        name: core-pod-editor
        url: https://bundles.byte.builders/ui/
        version: v0.4.0
