apiVersion: meta.k8s.appscode.com/v1alpha1
kind: Render
request:
  convertToTable: true
  layoutName: kubedb-kubedb.com-v1alpha2-mongodbs
  pageName: Operations
  source:
    ref:
      name: mg-sh
      namespace: demo
    resource:
      group: kubedb.com
      kind: MongoDB
      name: ""
      scope: ""
      version: ""
response:
  view:
    header:
      actions:
        create: Never
      kind: Connection
      resource:
        group: ui.k8s.appscode.com
        kind: GenericResource
        name: genericresources
        scope: Namespaced
        version: v1alpha1
      table:
        columns:
        - link: true
          name: Name
          sort:
            enable: true
            type: ""
          type: string
        - name: Namespace
          type: string
        - name: Labels
          type: object
        - name: Annotations
          type: object
        - name: Age
          sort:
            enable: true
            type: integer
          type: date
        - name: ClusterUID
          type: string
        - name: ClusterName
          type: string
        - name: Cluster Name
          type: string
        - name: Cluster Provider
          type: string
        - name: APIGroup
          type: string
        - name: APIVersion
          type: string
        - name: APIResource
          type: string
        - name: APIKind
          type: string
        - name: APIScope
          type: string
        - name: Version
          type: string
        - name: Replicas
          type: integer
        - name: Mode
          type: string
        - name: Total Resource Limits
          type: object
        - name: Total Resource Requests
          type: object
        - name: App Resource Limits
          type: object
        - name: App Resource Requests
          type: object
        - name: Status
          type: string
        - name: Age
          sort:
            enable: true
            type: integer
          type: date
        metadata: {}
        rows: []
    layoutName: kubedb-kubedb.com-v1alpha2-mongodbs
    pages:
    - blocks:
      - actions:
          create: Always
        kind: Connection
        resource:
          group: ops.kubedb.com
          kind: MongoDBOpsRequest
          name: mongodbopsrequests
          scope: Namespaced
          version: v1alpha1
        table:
          columns:
          - name: Name
            type: string
          - name: Namespace
            type: string
          - name: Labels
            type: object
          - name: Type
            type: string
          - name: Target Database
            type: string
          - name: Status
            type: string
          - name: Age
            sort:
              enable: true
              type: integer
            type: date
          metadata: {}
          rows: []
      name: Operations
    resource:
      group: kubedb.com
      kind: MongoDB
      name: mongodbs
      scope: Namespaced
      version: v1alpha2
    tabBar:
      actions:
        create: Never
      kind: Connection
      resource:
        group: ui.k8s.appscode.com
        kind: GenericResourceService
        name: genericresourceservices
        scope: Namespaced
        version: v1alpha1
      table:
        columns:
        - link: true
          name: Name
          sort:
            enable: true
            type: ""
          type: string
        - name: Namespace
          type: string
        - name: Labels
          type: object
        - name: Annotations
          type: object
        - name: Age
          sort:
            enable: true
            type: integer
          type: date
        - name: ClusterUID
          type: string
        - name: ClusterName
          type: string
        - name: Cluster Name
          type: string
        - name: Cluster Provider
          type: string
        - name: APIGroup
          type: string
        - name: APIVersion
          type: string
        - name: APIResource
          type: string
        - name: APIKind
          type: string
        - name: APIScope
          type: string
        - name: Exposed
          type: string
        - name: TLS
          type: string
        - name: Backup
          type: string
        - name: Monitoring
          type: string
        - name: Status
          type: string
        - name: Age
          sort:
            enable: true
            type: integer
          type: date
        metadata: {}
        rows: []
    ui:
      editor:
        name: kubedbcom-mongodb-editor
        url: https://bundles.byte.builders/ui/
        version: v0.3.0
      options:
        name: kubedbcom-mongodb-editor-options
        url: https://bundles.byte.builders/ui/
        version: v0.3.0
