apiVersion: meta.k8s.appscode.com/v1alpha1
kind: Render
request:
  block:
    displayMode: Field
    kind: Connection
    query:
      byLabel: view
      type: GraphQL
    ref:
      group: ui.kubedb.com
      kind: MongoDBInsight
    view: {}
  convertToTable: true
  source:
    ref:
      name: mg-rs
      namespace: default
    resource:
      group: kubedb.com
      kind: MongoDB
      name: ""
      scope: ""
      version: ""
response:
  block:
    kind: Connection
    resource:
      group: ui.kubedb.com
      kind: MongoDBInsight
      name: mongodbinsights
      scope: Namespaced
      version: v1alpha1
    result:
      status: Success
    table:
      columns:
      - name: Name
        priority: 3
        sort:
          enable: true
        type: string
      - name: Namespace
        priority: 3
        type: string
      - name: Labels
        priority: 3
        type: object
      - name: Annotations
        priority: 3
        type: object
      - name: Age
        priority: 3
        sort:
          enable: true
          type: integer
        type: date
      - name: Version
        priority: 3
        type: string
      - name: Type
        priority: 3
        type: string
      - name: Status
        priority: 3
        type: string
      - name: Current Connections
        priority: 3
        type: integer
      - name: Total Connections
        priority: 3
        type: integer
      - name: Available Connections
        priority: 3
        type: integer
      - name: Active Connections
        priority: 3
        type: integer
      - name: Total Collections
        priority: 3
        type: integer
      - name: Data Size
        priority: 3
        type: integer
      - name: Total Indexes
        priority: 3
        type: integer
      - name: Index Size
        priority: 3
        type: integer
      - name: Number Of Shards
        priority: 3
        type: integer
      - name: Replicas Per Shards
        priority: 3
        type: integer
      - name: Number Of Chunks
        priority: 3
        type: integer
      - name: Balancer Enabled
        priority: 3
        type: boolean
      - name: Chunks Balanced
        priority: 3
        type: boolean
      - name: Replicas
        priority: 3
        type: integer
      metadata: {}
      rows:
      - cells:
        - data: mg-rs
        - data: default
        - data: {}
        - data: {}
        - data: 2d9h
          sort: 1646039113
        - data: 4.4.6
        - data: ReplicaSet
        - data: Ready
        - data: 33
        - data: 180790
        - data: 838827
        - data: 5
        - data: 15
        - data: 3481922
        - data: 15
        - data: 299008
        - data: <unknown>
        - data: <unknown>
        - data: <unknown>
        - data: <unknown>
        - data: <unknown>
        - data: 3
