apiVersion: meta.k8s.appscode.com/v1alpha1
kind: Render
request:
  block:
    displayMode: Field
    kind: Connection
    query:
      raw: |-
        query Find($src: String!, $targetGroup: String!, $targetKind: String!) {
          find(oid: $src) {
            backup_via(group: "stash.appscode.com", kind: "BackupConfiguration") {
              refs: view(group: $targetGroup, kind: $targetKind) {
                namespace
                name
              }
            }
          }
        }
      type: GraphQL
    ref:
      group: ui.stash.appscode.com
      kind: BackupOverview
    view: {}
  convertToTable: true
  source:
    ref:
      name: mg-rs-demo
      namespace: demo
    resource:
      group: kubedb.com
      kind: MongoDB
      name: ""
      scope: ""
      version: ""
response:
  block:
    kind: Connection
    resource:
      group: ui.stash.appscode.com
      kind: BackupOverview
      name: backupoverviews
      scope: Namespaced
      version: v1alpha1
    result:
      status: Success
    table:
      columns:
      - name: Name
        priority: 3
        sort:
          enable: true
        type: string
      - name: Namespace
        priority: 3
        type: string
      - name: Labels
        priority: 3
        type: object
      - name: Annotations
        priority: 3
        type: object
      - name: Age
        priority: 3
        sort:
          enable: true
          type: integer
        type: date
      - name: Schedule
        priority: 3
        type: string
      - name: Status
        priority: 3
        type: string
      - name: Last Backup Time
        priority: 3
        sort:
          enable: true
          type: integer
        type: date
      - name: Upcoming Backup Time
        priority: 3
        sort:
          enable: true
          type: integer
        type: date
      - name: Repository
        priority: 3
        type: string
      - name: Data Size
        priority: 3
        type: string
      - name: Number Of Snapshots
        priority: 3
        type: integer
      - name: Data Integrity
        priority: 3
        type: boolean
      metadata: {}
      rows:
      - cells:
        - data: mg-rs-demo
        - data: demo
        - data:
            app.kubernetes.io/instance: mg-rs-demo
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: mongodbs.kubedb.com
        - data:
            meta.helm.sh/release-name: mg-rs-demo
            meta.helm.sh/release-namespace: demo
        - data: 16h
          sort: 1646225039
        - data: '"*/5 * * * *" (Every 5 minutes)'
        - data: Active
        - data: <unknown>
          sort: -62135596800
        - data: <invalid>
          sort: 1646284500
        - data: mg-rs-demo-repo
        - data: ""
        - data: <unknown>
        - data: <unknown>
