apiVersion: meta.k8s.appscode.com/v1alpha1
kind: Render
request:
  convertToTable: true
  layoutName: kubedb-kubedb.com-v1alpha2-mongodbs
  pageName: Operations
  source:
    ref:
      name: mg-sh
      namespace: demo
    resource:
      group: kubedb.com
      kind: MongoDB
      name: ""
      scope: ""
      version: ""
response:
  view:
    header:
      actions:
        create: Never
      kind: Connection
      resource:
        group: ui.k8s.appscode.com
        kind: GenericResource
        name: genericresources
        scope: Namespaced
        version: v1alpha1
      table:
        columns:
        - name: UID
          type: string
        - name: Name
          type: string
        - name: Display Name
          type: string
        - name: Provider
          type: string
        - name: Group
          type: string
        - name: Version
          type: string
        - name: Name
          type: string
        - name: Kind
          type: string
        - name: Scope
          type: string
        - name: Version
          type: string
        - name: Replicas
          type: integer
        - name: Role Replicas
          type: object
        - name: Mode
          type: string
        - name: Limits
          type: object
        - name: Requests
          type: object
        - name: Limits
          type: object
        - name: Requests
          type: object
        - name: Role Resource Limits
          type: object
        - name: Role Resource Requests
          type: object
        - name: Status
          type: string
        - name: Message
          type: string
        metadata: {}
        rows: []
    layoutName: kubedb-kubedb.com-v1alpha2-mongodbs
    pages:
    - blocks:
      - actions:
          create: Always
        kind: Connection
        resource:
          group: ops.kubedb.com
          kind: MongoDBOpsRequest
          name: mongodbopsrequests
          scope: Namespaced
          version: v1alpha1
        table:
          columns:
          - name: Name
            type: string
          - name: Namespace
            type: string
          - name: Labels
            type: object
          - name: Type
            type: string
          - name: Target Database
            type: string
          - name: Status
            type: string
          - name: Age
            type: date
          metadata: {}
          rows: []
      name: Operations
    resource:
      group: kubedb.com
      kind: MongoDB
      name: mongodbs
      scope: Namespaced
      version: v1alpha2
    tabBar:
      actions:
        create: Never
      kind: Connection
      resource:
        group: ui.k8s.appscode.com
        kind: GenericResourceService
        name: genericresourceservices
        scope: Namespaced
        version: v1alpha1
      table:
        columns:
        - name: Group
          type: string
        - name: Version
          type: string
        - name: Name
          type: string
        - name: Kind
          type: string
        - name: Scope
          type: string
        - name: Usage
          type: string
        - name: Group
          type: string
        - name: Version
          type: string
        - name: Name
          type: string
        - name: Kind
          type: string
        - name: Scope
          type: string
        - name: Namespace
          type: string
        - name: Name
          type: string
        - name: Usage
          type: string
        - name: Group
          type: string
        - name: Version
          type: string
        - name: Name
          type: string
        - name: Kind
          type: string
        - name: Scope
          type: string
        - name: Namespace
          type: string
        - name: Name
          type: string
        - name: Usage
          type: string
        - name: Group
          type: string
        - name: Version
          type: string
        - name: Name
          type: string
        - name: Kind
          type: string
        - name: Scope
          type: string
        - name: Namespace
          type: string
        - name: Name
          type: string
        - name: Usage
          type: string
        - name: Group
          type: string
        - name: Version
          type: string
        - name: Name
          type: string
        - name: Kind
          type: string
        - name: Scope
          type: string
        - name: Namespace
          type: string
        - name: Name
          type: string
        - name: Status
          type: string
        - name: Message
          type: string
        metadata: {}
        rows: []
    ui:
      editor:
        name: kubedbcom-mongodb-editor
        url: https://bundles.byte.builders/ui/
        version: v0.3.0
      options:
        name: kubedbcom-mongodb-editor-options
        url: https://bundles.byte.builders/ui/
        version: v0.3.0
