apiVersion: meta.k8s.appscode.com/v1alpha1
kind: Render
request:
  source:
    resource:
      group: kubedb.com
      version: v1alpha2
      name: postgreses
    ref:
      namespace: demo
      name: pg-std
  layoutName: kubedb.com-v1alpha2-postgreses-kubedb
  pageName: Database Insights
  convertToTable: true
  renderBlocks:
  - Connection

# apiVersion: meta.k8s.appscode.com/v1alpha1
# kind: Render
# request:
#   source:
#     resource:
#       group: kubedb.com
#       version: v1alpha2
#       name: mongodbs
#     ref:
#       namespace: demo
#       name: mg-sh
#   layoutName: kubedb.com-v1alpha2-mongodbs-kubedb
#   pageName: Overview
#   convertToTable: true
#   renderBlocks:
#   - Connection

  # block:
  #   displayMode: List
  #   kind: Connection
  #   name: Pods
  #   query:
  #     raw: |-
  #       query Find($src: String!, $targetGroup: String!, $targetKind: String!) {
  #         find(oid: $src) {
  #           offshoot(group: "", kind: "Pod") {
  #             refs: view(group: $targetGroup, kind: $targetKind) {
  #               namespace
  #               name
  #             }
  #           }
  #         }
  #       }
  #     type: GraphQL
  #   ref:
  #     group: core.k8s.appscode.com
  #     kind: PodView


# apiVersion: meta.k8s.appscode.com/v1alpha1
# kind: Render
# request:
#   source:
#     ref:
#       name: mg-sh
#       namespace: demo
#     resource:
#       group: kubedb.com
#       kind: MongoDB
#       name: ""
#       scope: ""
#       version: ""
#   block:
#     displayMode: List
#     kind: Connection
#     query:
#       raw: |
#         request:
#           resource:
#             group: kubedb.com
#             name: mongodbs
#             version: v1alpha2
#           ref:
#             name: {{ .name }}
#             namespace: {{ .namespace }}
#           name: kubedb.com-v1alpha2-mongodbs
#       type: REST
#     ref:
#       group: meta.k8s.appscode.com
#       kind: RenderDashboard
#     fieldPath: .response.dashboards
#     view:
#       # name: ui.openviz.dev-v1alpha1-dashboardgroups-panels
#       columns:
#       - name: Title
#         pathTemplate: '{{ .title }}'
#         priority: 3
#         type: string
#       - name: URL
#         pathTemplate: '{{ .url }}'
#         priority: 3
#         type: string
#   convertToTable: true



# apiVersion: meta.k8s.appscode.com/v1alpha1
# kind: Render
# request:
#   source:
#     ref:
#       name: mg-sh
#       namespace: demo
#     resource:
#       group: kubedb.com
#       kind: MongoDB
#       name: ""
#       scope: ""
#       version: ""
#   block:
#     displayMode: List
#     fieldPath: '{.response.dashboards[0].panels}'
#     kind: Connection
#     query:
#       raw: |
#         request:
#           embeddedLink: true
#           dashboards:
#           - title: "KubeDB / MongoDB / Summary"
#             vars:
#             - name: namespace
#               value: {{ .namespace }}
#             - name: db
#               value: {{ .name }}
#             panels:
#               - { "title": "CPU Usage", "width": 12 }
#               - { "title": "Memory Usage", "width": 12 }
#               - { "title": "Disk Usage", "width": 6 }
#               - { "title": "Disk R/W Info", "width": 6 }
#               - { "title": "IOPS (Reads+Writes)", "width": 6 }
#               - { "title": "ThroughPut (Read+Write)", "width": 6 }
#               - { "title": "Receive Bandwidth", "width": 6 }
#               - { "title": "Transmit Bandwidth", "width": 6 }
#       type: REST
#     ref:
#       group: ui.openviz.dev
#       kind: DashboardGroup
#     view:
#       # name: ui.openviz.dev-v1alpha1-dashboardgroups-panels
#       columns:
#       - name: Title
#         pathTemplate: '{{ .title }}'
#         priority: 3
#         type: string
#       - name: URL
#         pathTemplate: '{{ .url }}'
#         priority: 3
#         type: string
#       - name: Width
#         pathTemplate: '{{ .width }}'
#         priority: 3
#         type: integer
#   convertToTable: true



# apiVersion: meta.k8s.appscode.com/v1alpha1
# kind: Render
# request:
#   source:
#     resource:
#       group: core
#       version: v1
#       name: pods
#     ref:
#       namespace: default
#       name: mg-rs-0
#   layoutName: core-v1-pods
#   pageName: Basic
#   convertToTable: true
#   renderBlocks:
#   - Self


# apiVersion: meta.k8s.appscode.com/v1alpha1
# kind: Render
# request:
#   source:
#     resource:
#       group: kubedb.com
#       kind: MongoDB
#     ref:
#       name: mg-sh
#       namespace: demo
#   # layoutName: kubedb-kubedb.com-v1alpha2-mongodbs
#   convertToTable: true

# apiVersion: meta.k8s.appscode.com/v1alpha1
# kind: Render
# request:
#   source:
#     resource:
#       group: kubedb.com
#       version: v1alpha2
#       name: mongodbs
#     ref:
#       namespace: demo
#       name: mg-std
#   layoutName: kubedb-kubedb.com-v1alpha2-mongodbs
#   pageName: Database Insights
#   convertToTable: true
#   renderBlocks:
#   - Connection


  # block:
  #   displayMode: List
  #   kind: Connection
  #   query:
  #     raw: |
  #       request:
  #         target:
  #           group: kubedb.com
  #           kind: MongoDB
  #           name: {{ .name }}
  #           namespace: {{ .namespace }}
  #         dashboard:
  #           title: "KubeDB / MongoDB / Summary"
  #         panels: []
  #     type: REST
  #   ref:
  #     group: ui.openviz.dev
  #     kind: EmbeddedDashboard
  #   fieldPath: .response.urls
  #   view:
  #     columns:
  #     - name: Title
  #       pathTemplate: '{{ .title }}'
  #       priority: 3
  #       type: string
  #     - name: Embedded URL
  #       pathTemplate: '{{ .embeddedURL }}'
  #       priority: 3
  #       type: string

  # block:
  #   displayMode: List
  #   kind: Connection
  #   name: AppBinding
  #   query:
  #     type: GraphQL
  #     byLabel: offshoot
  #   ref:
  #     group: appcatalog.appscode.com
  #     kind: AppBinding

  # block:
  #   displayMode: List
  #   kind: Connection
  #   name: Pods
  #   query:
  #     type: GraphQL
  #     byLabel: offshoot
  #   ref:
  #     group: ""
  #     kind: Pod


  # block:
  #   displayMode: Field
  #   kind: Connection
  #   query:
  #     byLabel: view
  #     type: GraphQL
  #   ref:
  #     group: ui.kubedb.com
  #     kind: MongoDBInsight


  # block:
  #   displayMode: List
  #   kind: Connection
  #   name: Recent Backups
  #   query:
  #     raw: |-
  #       query Find($src: String!, $targetGroup: String!, $targetKind: String!) {
  #         find(oid: $src) {
  #           backup_via(group: "stash.appscode.com", kind: "BackupConfiguration") {
  #             refs: offshoot(group: $targetGroup, kind: $targetKind) {
  #               namespace
  #               name
  #             }
  #           }
  #         }
  #       }
  #     type: GraphQL
  #   ref:
  #     group: stash.appscode.com
  #     kind: BackupSession

  # block:
  #   displayMode: Field
  #   kind: Connection
  #   query:
  #     raw: |-
  #       query Find($src: String!, $targetGroup: String!, $targetKind: String!) {
  #         find(oid: $src) {
  #           backup_via(group: "stash.appscode.com", kind: "BackupConfiguration") {
  #             refs: view(group: $targetGroup, kind: $targetKind) {
  #               namespace
  #               name
  #             }
  #           }
  #         }
  #       }
  #     type: GraphQL
  #   ref:
  #     group: ui.stash.appscode.com
  #     kind: BackupOverview
