apiVersion: meta.k8s.appscode.com/v1alpha1
kind: Render
request:
  block:
    displayMode: List
    kind: Connection
    name: Pods
    query:
      raw: |-
        query Find($src: String!, $targetGroup: String!, $targetKind: String!) {
          find(oid: $src) {
            offshoot(group: "", kind: "Pod") {
              refs: view(group: $targetGroup, kind: $targetKind) {
                namespace
                name
              }
            }
          }
        }
      type: GraphQL
    ref:
      group: core.k8s.appscode.com
      kind: PodView
    view: {}
  convertToTable: true
  source:
    ref:
      name: mgo-rs
      namespace: default
    resource:
      group: kubedb.com
      kind: MongoDB
      name: ""
      scope: ""
      version: ""
response:
  block:
    kind: Connection
    name: Pods
    resource:
      group: core.k8s.appscode.com
      kind: PodView
      name: podviews
      scope: Namespaced
      version: v1alpha1
    result:
      status: Success
    table:
      columns:
      - format: name
        name: Name
        priority: 3
        type: string
      - name: Namespace
        priority: 3
        type: string
      - name: Labels
        priority: 3
        type: object
      - name: Limits
        priority: 3
        type: object
      - name: Requests
        priority: 3
        type: object
      - name: Usage
        priority: 3
        type: object
      - name: Age
        priority: 3
        sort:
          enable: true
          type: integer
        type: date
      metadata: {}
      rows:
      - cells:
        - data: mgo-rs-0
        - data: default
        - data:
            app.kubernetes.io/component: database
            app.kubernetes.io/instance: mgo-rs
            app.kubernetes.io/managed-by: kubedb.com
            app.kubernetes.io/name: mongodbs.kubedb.com
            controller-revision-hash: mgo-rs-6bf8fd8d56
            kubedb.com/role: primary
            statefulset.kubernetes.io/pod-name: mgo-rs-0
        - data: {}
        - data: {}
        - data: {}
        - data: 8h
          sort: 1646183050
      - cells:
        - data: mgo-rs-1
        - data: default
        - data:
            app.kubernetes.io/component: database
            app.kubernetes.io/instance: mgo-rs
            app.kubernetes.io/managed-by: kubedb.com
            app.kubernetes.io/name: mongodbs.kubedb.com
            controller-revision-hash: mgo-rs-6bf8fd8d56
            kubedb.com/role: standby
            statefulset.kubernetes.io/pod-name: mgo-rs-1
        - data: {}
        - data: {}
        - data: {}
        - data: 8h
          sort: 1646183134
      - cells:
        - data: mgo-rs-2
        - data: default
        - data:
            app.kubernetes.io/component: database
            app.kubernetes.io/instance: mgo-rs
            app.kubernetes.io/managed-by: kubedb.com
            app.kubernetes.io/name: mongodbs.kubedb.com
            controller-revision-hash: mgo-rs-6bf8fd8d56
            kubedb.com/role: standby
            statefulset.kubernetes.io/pod-name: mgo-rs-2
        - data: {}
        - data: {}
        - data: {}
        - data: 8h
          sort: 1646183162
