apiVersion: meta.k8s.appscode.com/v1alpha1
kind: Render
request:
  convertToTable: true
  layoutName: core-v1-pods
  pageName: Basic
  renderBlocks:
  - Self
  source:
    ref:
      name: mg-rs-0
      namespace: default
    resource:
      group: core
      kind: ""
      name: pods
      scope: ""
      version: v1
response:
  view:
    layoutName: core-v1-pods
    pages:
    - info:
        kind: Self
        resource:
          group: ""
          kind: Pod
          name: pods
          scope: Namespaced
          version: v1
        result:
          message: 'falied to render column {Name:Age Type:integer Template:{{ .metadata.creationTimestamp
            | toDate "2006-01-02T15:04:05Z07:00" | unixEpoch }}}: template: :1:33:
            executing "" at <toDate "2006-01-02T15:04:05Z07:00">: error calling toDate:
            reflect: call of reflect.Value.IsNil on string Value'
          status: Error
      name: Basic
    resource:
      group: ""
      kind: Pod
      name: pods
      scope: Namespaced
      version: v1
    ui:
      editor:
        name: core-pod-editor
        url: https://bundles.byte.builders/ui/
        version: v0.4.0
