apiVersion: meta.k8s.appscode.com/v1alpha1
kind: RenderSection
request:
  source:
    group: apps
    kind: Deployment
    namespace: kube-system
    name: coredns
  target:
    query:
      byLabel: offshoot
    # ref:
    #   group: ""
    #   kind: Pod
    ref:
      group: apps
      kind: ReplicaSet
  convertToTable: true
