apiVersion: meta.k8s.appscode.com/v1alpha1
kind: Render
request:
  source:
    resource:
      group: kubedb.com
      kind: MongoDB
    ref:
      name: mg-rs
      namespace: default
  # layoutName: kubedb-kubedb.com-v1alpha2-mongodbs
  convertToTable: true

  # block:
  #   displayMode: List
  #   kind: Connection
  #   name: AppBinding
  #   query:
  #     type: GraphQL
  #     byLabel: offshoot
  #   ref:
  #     group: appcatalog.appscode.com
  #     kind: AppBinding

  # block:
  #   displayMode: List
  #   kind: Connection
  #   name: Pods
  #   query:
  #     type: GraphQL
  #     byLabel: offshoot
  #   ref:
  #     group: ""
  #     kind: Pod

  # block:
  #   displayMode: List
  #   kind: Connection
  #   name: Pods
  #   query:
  #     raw: |-
  #       query Find($src: String!, $targetGroup: String!, $targetKind: String!) {
  #         find(oid: $src) {
  #           offshoot(group: "", kind: "Pod") {
  #             refs: view(group: $targetGroup, kind: $targetKind) {
  #               namespace
  #               name
  #             }
  #           }
  #         }
  #       }
  #     type: GraphQL
  #   ref:
  #     group: core.k8s.appscode.com
  #     kind: PodView

  block:
    displayMode: Field
    kind: Connection
    query:
      byLabel: view
      type: GraphQL
    ref:
      group: ui.kubedb.com
      kind: MongoDBInsight
