apiVersion: meta.k8s.appscode.com/v1alpha1
kind: Render
request:
  source:
    resource:
      group: kubedb.com
      kind: MongoDB
    ref:
      namespace: demo
      name: mg-sh
  layoutName: kubedb-kubedb.com-v1alpha2-mongodbs


    # group: ""
    # kind: Pod
    # namespace: kube-system
    # name: coredns-65648f44c6-b55n8
    # name: calico-kube-controllers
    # group: apps
    # kind: Deployment
    # namespace: kube-system
    # name: coredns
    # name: calico-kube-controllers

  # block:
  #   kind: 
  #   query:
  #     type: GraphQL
  #     byLabel: exposed_by
  #   ref:
  #     group: ""
  #     kind: Service
  #   # ref:
  #   #   group: ""
  #   #   kind: Pod
  #   # ref:
  #   #   group: apps
  #   #   kind: ReplicaSet
  convertToTable: true
