apiVersion: meta.k8s.appscode.com/v1alpha1
kind: Menu
metadata:
  creationTimestamp: null
  name: kubedb
  uid: 83a07170-905a-11ec-bea0-a2ec65cee26a
spec:
  home:
    name: Home
    path: /
  mode: Accordion
  sections:
  - icons:
    - src: https://cdn.appscode.com/k8s/icons/menu/datastore.svg
      type: image/svg+xml
    - src: https://cdn.appscode.com/k8s/icons/menu/datastore.png
      type: image/png
    items:
    - icons:
      - src: https://cdn.appscode.com/k8s/icons/kubedb.com/elasticsearches.svg
        type: image/svg+xml
      - src: https://cdn.appscode.com/k8s/icons/kubedb.com/elasticsearches.png
        type: image/png
      layoutName: kubedb-kubedb.com-v1alpha2-elasticsearches
      missing: true
      name: Elasticsearch
      required: true
      resource:
        group: kubedb.com
        kind: Elasticsearch
        name: elasticsearches
        scope: Namespaced
        version: v1alpha2
    - icons:
      - src: https://cdn.appscode.com/k8s/icons/kubedb.com/mariadbs.svg
        type: image/svg+xml
      - src: https://cdn.appscode.com/k8s/icons/kubedb.com/mariadbs.png
        type: image/png
      layoutName: kubedb-kubedb.com-v1alpha2-mariadbs
      name: MariaDB
      required: true
      resource:
        group: kubedb.com
        kind: MariaDB
        name: mariadbs
        scope: Namespaced
        version: v1alpha2
    - icons:
      - src: https://cdn.appscode.com/k8s/icons/kubedb.com/memcacheds.svg
        type: image/svg+xml
      - src: https://cdn.appscode.com/k8s/icons/kubedb.com/memcacheds.png
        type: image/png
      layoutName: kubedb-kubedb.com-v1alpha2-memcacheds
      missing: true
      name: Memcached
      required: true
      resource:
        group: kubedb.com
        kind: Memcached
        name: memcacheds
        scope: Namespaced
        version: v1alpha2
    - icons:
      - src: https://cdn.appscode.com/k8s/icons/kubedb.com/mongodbs.svg
        type: image/svg+xml
      - src: https://cdn.appscode.com/k8s/icons/kubedb.com/mongodbs.png
        type: image/png
      layoutName: kubedb-kubedb.com-v1alpha2-mongodbs
      name: MongoDB
      required: true
      resource:
        group: kubedb.com
        kind: MongoDB
        name: mongodbs
        scope: Namespaced
        version: v1alpha2
    - icons:
      - src: https://cdn.appscode.com/k8s/icons/kubedb.com/mysqls.svg
        type: image/svg+xml
      - src: https://cdn.appscode.com/k8s/icons/kubedb.com/mysqls.png
        type: image/png
      layoutName: kubedb-kubedb.com-v1alpha2-mysqls
      name: MySQL
      required: true
      resource:
        group: kubedb.com
        kind: MySQL
        name: mysqls
        scope: Namespaced
        version: v1alpha2
    - icons:
      - src: https://cdn.appscode.com/k8s/icons/kubedb.com/postgreses.svg
        type: image/svg+xml
      - src: https://cdn.appscode.com/k8s/icons/kubedb.com/postgreses.png
        type: image/png
      layoutName: kubedb-kubedb.com-v1alpha2-postgreses
      name: PostgreSQL
      required: true
      resource:
        group: kubedb.com
        kind: Postgres
        name: postgreses
        scope: Namespaced
        version: v1alpha2
    - icons:
      - src: https://cdn.appscode.com/k8s/icons/kubedb.com/redises.svg
        type: image/svg+xml
      - src: https://cdn.appscode.com/k8s/icons/kubedb.com/redises.png
        type: image/png
      layoutName: kubedb-kubedb.com-v1alpha2-redises
      missing: true
      name: Redis
      required: true
      resource:
        group: kubedb.com
        kind: Redis
        name: redises
        scope: Namespaced
        version: v1alpha2
    name: Datastore
    path: /ui.appscode.com/v1alpha1/sections/datastore
  - icons:
    - src: https://cdn.appscode.com/k8s/icons/menu/datastore.svg
      type: image/svg+xml
    - src: https://cdn.appscode.com/k8s/icons/menu/datastore.png
      type: image/png
    items:
    - icons:
      - src: https://cdn.appscode.com/k8s/icons/kubedb.com/mongodbs.svg
        type: image/svg+xml
      - src: https://cdn.appscode.com/k8s/icons/kubedb.com/mongodbs.png
        type: image/png
      layoutName: kubedb-kubedb.com-v1alpha2-mongodbs
      name: Backups
      resource:
        group: kubedb.com
        kind: MongoDB
        name: mongodbs
        scope: Namespaced
        version: v1alpha2
    name: Backups
    path: /ui.appscode.com/v1alpha1/sections/backups
